import { Service } from "@/types/service";
import { Car, Droplets, Shield, Sparkles, Wrench } from "lucide-react";

export const services: Service[] = [
  {
    id: "1",
    name: "Higienização Interna Completa",
    description: "Limpeza profunda de todo o interior do veículo",
    priceRange: "R$ 300 a R$ 500",
    category: "Premium",
    icon: <Car className="h-5 w-5" />,
    image: "/images/higienizacao-interna.png",
    items: [
      { text: "Limpeza técnica nos bancos (tecido ou couro)", included: true },
      { text: "Limpeza e hidratação dos painéis", included: true },
      { text: "Limpeza de teto", included: true },
      { text: "Higienização dos plásticos internos", included: true },
      { text: "Limpeza das saídas de ar, cintos e pedais", included: true },
      { text: "Eliminação de ácaros, fungos e bactérias", included: true },
      { text: "Aromatização especial", included: true },
    ],
    whatsappMessage:
      "Olá! Gostaria de agendar uma *Higienização Interna Completa* (R$ 300 a R$ 500). Quando vocês têm disponibilidade?",
  },
  {
    id: "2",
    name: "Lavagem Completa Premium",
    description: "Lavagem externa e interna com produtos premium",
    priceRange: "R$ 80 a R$ 120",
    category: "Lavagem",
    icon: <Droplets className="h-5 w-5" />,
    image: "/placeholder.svg?height=200&width=300",
    items: [
      { text: "Pré-lavagem com espuma ativa", included: true },
      { text: "Lavagem com shampoo neutro premium", included: true },
      { text: "Limpeza de rodas e pneus", included: true },
      { text: "Secagem com flanela de microfibra", included: true },
      { text: "Limpeza dos vidros internos e externos", included: true },
      { text: "Aspiração completa do interior", included: true },
      { text: "Limpeza do painel e console", included: true },
    ],
    whatsappMessage:
      "Olá! Tenho interesse na *Lavagem Completa Premium* (R$ 80 a R$ 120). Podem me passar mais informações?",
  },
  {
    id: "3",
    name: "Enceramento com Cera de Carnaúba",
    description: "Proteção e brilho duradouro com cera premium",
    priceRange: "R$ 150 a R$ 250",
    category: "Proteção",
    icon: <Shield className="h-5 w-5" />,
    image: "/placeholder.svg?height=200&width=300",
    items: [
      { text: "Lavagem completa prévia", included: true },
      { text: "Descontaminação da pintura", included: true },
      { text: "Aplicação de cera de carnaúba premium", included: true },
      { text: "Polimento manual", included: true },
      { text: "Proteção dos plásticos externos", included: true },
      { text: "Finalização com microfibra", included: true },
      { text: "Durabilidade de 3 a 4 meses", included: true },
    ],
    whatsappMessage:
      "Olá! Gostaria de fazer um *Enceramento com Cera de Carnaúba* (R$ 150 a R$ 250). Qual a disponibilidade?",
  },
  {
    id: "4",
    name: "Detalhamento Completo",
    description: "Serviço completo de estética automotiva",
    priceRange: "R$ 400 a R$ 800",
    category: "Premium",
    icon: <Sparkles className="h-5 w-5" />,
    image: "/placeholder.svg?height=200&width=300",
    items: [
      { text: "Lavagem completa externa e interna", included: true },
      { text: "Higienização completa do interior", included: true },
      { text: "Enceramento com cera premium", included: true },
      { text: "Polimento da pintura", included: true },
      { text: "Tratamento de couro (se aplicável)", included: true },
      { text: "Limpeza do motor", included: true },
      { text: "Proteção dos pneus", included: true },
      { text: "Aromatização especial", included: true },
    ],
    whatsappMessage:
      "Olá! Tenho interesse no *Detalhamento Completo* (R$ 400 a R$ 800). Quanto tempo demora o serviço?",
  },
  {
    id: "5",
    name: "Lavagem Ecológica",
    description: "Lavagem sustentável com economia de água",
    priceRange: "R$ 60 a R$ 90",
    category: "Eco",
    icon: <Droplets className="h-5 w-5" />,
    image: "/placeholder.svg?height=200&width=300",
    items: [
      { text: "Produtos biodegradáveis", included: true },
      { text: "Economia de até 90% de água", included: true },
      { text: "Lavagem externa completa", included: true },
      { text: "Limpeza de rodas e pneus", included: true },
      { text: "Aspiração do interior", included: true },
      { text: "Limpeza dos vidros", included: true },
      { text: "Processo sustentável certificado", included: true },
    ],
    whatsappMessage:
      "Olá! Gostaria de fazer uma *Lavagem Ecológica* (R$ 60 a R$ 90). Vocês atendem hoje?",
  },
  {
    id: "6",
    name: "Restauração de Faróis",
    description: "Recuperação do brilho e transparência dos faróis",
    priceRange: "R$ 120 a R$ 180",
    category: "Especializado",
    icon: <Wrench className="h-5 w-5" />,
    image: "/placeholder.svg?height=200&width=300",
    items: [
      { text: "Lixamento progressivo especializado", included: true },
      { text: "Polimento com pasta abrasiva", included: true },
      { text: "Aplicação de verniz protetor UV", included: true },
      { text: "Melhora na iluminação noturna", included: true },
      { text: "Remoção de amarelamento", included: true },
      { text: "Garantia de 12 meses", included: true },
      { text: "Teste de qualidade final", included: true },
    ],
    whatsappMessage:
      "Olá! Preciso fazer uma *Restauração de Faróis* (R$ 120 a R$ 180). Vocês fazem esse serviço?",
  },
];
